### PR TITLE
macOS updated info

### PR DESCRIPTION
**Pull request by mizuOda**
- updated macOS minimum system requirements
- added how to unpack .txz on Catalina
- minor edits
- also deleted unnecessary line breaks, which makes some sections entirely green when in fact no text actually changed :/

Note: I couldn't figure out a way to proofread my changes with the web page formatting, so can't be absolutely certain the formatting is okay. If there's a way for me to proofread with web page formatting before making a pull request, I would love to learn how to do that.

### CODE REVIEW

**Comment by dougmassay** [comment]
This looks good, thanks!

As to how to preview how the website will look after jekyll/github-pages builds the content: it's a nightmare of installing ruby and its "gems" and jekyll itself (and setting environment variables and adjusting paths), that is hardly worth the trouble in my opinion. I tend to make small changes and then simply revert them if it breaks something! :)

If you're on Big Sur, you should already have a compatible version of Ruby installed, so you could skip the ruby installation section and jump to the Install Jekyll section (Local Install) <https://jekyllrb.com/docs/installation/macos/>. But earlier than Big Sur, you'll probably want to use some sort of package manager to install a compatible version of Ruby (github-pages doesn't support Ruby 3, so 2.7.x is usually sufficient).

If you get as far as getting jekyll installed, I'll be happy to tell you how to serve up the site locally so you can preview your changes.

You can get a general idea of how the markdown of a page will look with an editor that supports/previews markdown. but it won't have all the theme stuff (colors, css, etc...).

**Comment by kevinhendricks** [comment]
Doitsu has a Markdown Input plugin for Sigil that uses github's version of markdown.  I am not sure he released it but I have a copy of it.  Would we be able to view the site in Sigil usung the MarkDown plugin?

**Comment by dougmassay** [comment]
Not really. Might be able to see how one page renders (sans any css or theme-related custom navigation and or styles). Github pages generates the actual served site (using jekyll) with each push to sigil-ebook.github.io. The only way to truly preview the site (exactly as it will be rendered) locally before pushing commits is to configure and use ruby/jekyll to build the site and serve it locally.

**Comment by dougmassay** [comment]
If you can get Ruby installed using one of the methods discussed in [the Jekyll documentation](https://jekyllrb.com/docs/installation/macos/) (has to be < than 3.0.0 to work with github pages). Then everything is pretty trivial from there. Big Sur is good to go with Ruby 2.6.x pre-installed. Just stay away from 3.0.0 (or use rbenv where you can have several versions installed).

I used rbenv on my Linux system. I understand it can be installed with Homebrew on Macs (if you don't want to build it from scratch).

Once that's done and its /bin directory is on your PATH (also in the documentation), you can install a couple of gems and be ready to serve up the local github repository/fork for viewing pretty easily.

Happy to help if anyone wants to try. I've successfully got it going on Linux and  Windows.

**Comment by mizuOda** [comment]
Umm ... umm ... umm ... you lost me at ruby and jekyll. I did recently upgrade to Catalina, but I'm nowhere near willing to jump to Big Sur :)

I edited the markdown in BBEdit, which has a markdown previewer, so that helped. Sometimes I also preview markdown files by dragging them into a Safari window. So I can at least get a generic look at what the markdown is looking like without theme stuff.

**Comment by dougmassay** [comment]
Been thinking about this a lot. How do you folks feel about Docker on a Mac? It's probably overkill--size-wise, but I've got a way that you (or anyone) could use a docker container that would set everything up (ruby, jekyll, and all the various github-pages gems) and would serve up the website locally.

The initial image download and run would take a bit of time to get everything set up, but then most of it could be cached so subsequent runs would be much, much quicker. You'd just have to cd into the local github repo, issue a command to start the container, and then open a browser to localhost:4000.

**Comment by mizuOda** [comment]
I think Docker is beyond my tech skills and comfort level  :)

**Pull request merged**
